# Generated by Django 5.0.2 on 2024-03-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_phone_customer_mobile'),
        ('orders', '0007_order_cancelled_at_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
    ]
